### ISSUE TITLE
clarify use case a smidge more?

### ISSUE THREAD

**Issue by evbo** [phiresky/sqlite-zstd#15]
I read your blog where it seems you compressed a _row_ including integer column types as well as json data, but in github readme it says data must be either text or blob?

I have a huge read only database of mostly integers and doubles, with a single row being easily over 15 - 20 bytes as recommended according to your blog. Could this still work or would I have to convert all of my integers to strings?

**Comment by phiresky** [comment]
It only compresses text/blob columns. I guess you're right that it was unclear in the blog post: I'm always referring to the size of a single cell in the table (one column of one row), not the total row size. The compression in this tool does not span multiple columns and will only work for `text` and `blob` columns.

For ints the sqlite-internal varint representation should already help you some. You can also try sqlite_zstd_vfs, that might help your use case.

**Comment by evbo** [comment]
sqlite_zstd_vfs is incredible, and it fits my use case perfectly thank you.
