### ISSUE TITLE
Can't enable transparent compression on the same table with different columns

### ISSUE THREAD

**Issue by biaocy** [phiresky/sqlite-zstd#6]
First of all, thank you for developing this brilliant extension.

I'm trying to compress a 300MB sqlite table with more than 50 columns in it.
I'm started with enable transparent compression on one column at a time,
but when I trying to enable the second column, it returns an error message `Error: data is a view not a table`.

Am I doing it wrong?

**Comment by phiresky** [comment]
It *should* work on multiple columns, but I didn't extensively test that functionality (maybe I broke it with new code). Can you try enabling debug logging by setting env var `RUST_LOG=sqlite_zstd=debug` and send what exactly you executed and what it outputs?

**Comment by biaocy** [comment]
Sorry for the late response.

I noticed the `multiple columns` feature was merged in [this commit](https://github.com/phiresky/sqlite-zstd/commit/1a76081f62d7616f164a40852c7bc5ca3821d0f3) which was happened on `Sep 16, 2021`,
but the latest release was published on `Jan 25, 2021`.

So the `multiple columns` feature was not in the latest release, hence the error message `Error: data is a view not a table` was reported.

Then I'm tried to build the extension on my computer with this command `cargo build --release`,
I tried the master branch and the `multiple columns`  commit and the tag v0.1.1,
all reported the same error message `Error: <the path>/libsqlite_zstd.so: undefined symbol: sqlite3_sqlitezstd_init` when I load the so file in sqlite3.

Are there anything I missed when building the extension?

The tool's information:
```bash
rustc 1.61.0 (fe5b13d68 2022-05-18)
cargo 1.61.0 (a028ae4 2022-04-29)
```

**Comment by biaocy** [comment]
I found the answer, at last. Sorry, I'm not familiar with rust.

It needs to specify the feature we are building.
So the correct command for building the extension now is `cargo build --releases --feature build_extension`.

The `multiple columns` feature works, after using the so file built with master branch.

But I have a new question.
After I'm enable compression on all the columns I want to compress, the sqlite3 database file's size was not decreased, but increased about 85MB.

Is this desired?
By the way, I'm not specify the column type when I'm creating the table except the primary key column, and all the column I'm compressing contains string data, so the affinity of the column was text type

**Comment by phiresky** [comment]
> Is this desired?

No, that's not expected. Did you call the `zstd_incremental_maintenance(7200, 0)` function? Without it the existing data is not actually compressed.  

Also try running `sqlite3 x.db VACUUM` to make sure sqlite clears up unused space.

If it's still larger, the data is either not compressible (does it get smaller if you zip the whole db file?) or there's an issue/bug somewhere.

If you could send over the your database file that would also be helpful.

**Comment by biaocy** [comment]
Yes, it works, after called the `zstd_incremental_maintenance` function, and `VACCUM` the database.

I reconstruct my table schema, the new table orignal size was __846MB__, it's __72MB__ after the compression.

> If you could send over the your database file that would also be helpful.

Sorry, I can't share my database because there're some sensitive data in it.

**Comment by phiresky** [comment]
That's great to hear!

>  I can't share my database

No problem. Make sure you don't trust important data with this tool as it's not really well tested and might eat your data.
