### ISSUE TITLE
Is it possible to cross compile android target?

### ISSUE THREAD

**Issue by biaocy** [phiresky/sqlite-zstd#7]
Hi, phiresky

I'm planning to cross compile this extension to android target, is it possible?

Currently, I'm trying to cross complie using [this doc](https://rust-lang.github.io/rustup/cross-compilation.html).

**Comment by phiresky** [comment]
In general it should work, but I don't know if you need to tweak any settings for compiling zstd or something.

**Comment by biaocy** [comment]
After some digging on the internet, I'm cross-compiled this extension for my android device, finally.

I'll sum it up here the procedure after I clean up my environment and sort out a way to use cargo configuration file.

**Comment by phiresky** [comment]
Great! Would be neat if you could post some info about it since it also might be interesting for other cross-compiling adventures. If you're willing to say, I'd also be interested in what you're planning on using this for ;)

**Comment by biaocy** [comment]
In order to cross-compile, we need to
1. Download the target we need to cross-compile, eg. `rustup target add aarch64_linux_android`
2. Prepare the [Android NDK](https://developer.android.com/tools/sdk/ndk/index.html)
3. Setup NDK binary path
```bash
# The NDK binary path vary depends on the NDK version and the host OS (I'm cross-compiled under WSL2)
export PATH=$PATH:<NDK DIR>/toolchains/llvm/prebuilt/linux-x86_64/bin
```
4. Setup linker
```bash
# The environment variable name vary depends on the target you cross-compile
export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=aarch64-linux-android23-clang
```
or specify the linker in the [cargo configuration file](https://doc.rust-lang.org/cargo/reference/config.html)
```toml
[target.aarch64-linux-android]
linker = "aarch64-linux-android23-clang"
```
5. Specify `target` accordingly when building
```bash
cargo build -r --features build_extension --target aarch64-linux-android
```


> What you're planning on using this for

I can't say it in detail, but I have a 800M database, after using this extension, the database's size shrink to 72M.
That's enough for us to find a way to using this extension on mobile device.
